version: '3'

services:
  api:
    image: spring-api
    build:
      context: "."
    ports:
      - "8080:8080"
    environment:
      JAVA_ENV: local
  db:
    image: postgres:9.6.16
    restart: always
    environment: 
      POSTGRES_PASSWORD: "flyway"
      POSTGRES_USER: "flyway"
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway:6.0.8-alpine
    volumes:
      - ../migrations/migration:/flyway/sql
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=test -user=flyway -password=flyway -connectRetries=60 migrate
